### ISSUE TITLE
Cannot find name 'DataViewScopeIdentity'

### ISSUE THREAD

**Issue by banban** [Microsoft/powerbi-visuals-sunburst#28]
Here is exceptions when I run pbiviz start:
info   Building visual...
error  TYPESCRIPT  /src/sunburst.ts : (485,27) Cannot find name 'DataViewScopeIdentity'.                                                                             method from exported c error  TYPESCRIPT  /src/sunburst.ts : (485,27) Parameter 'pathIdentity' of public
method from exported class has or is using private name 'DataViewScopeIdentity'.   tity'.
error  TYPESCRIPT  /src/sunburst.ts : (502,45) Cannot find name 'DataViewScopeIdentity'.

As mentioned in change [log v2.1.0](https://github.com/Microsoft/PowerBI-visuals-tools/blob/master/Changelog.md):
The DataViewScopeIdentity interface is no longer supported, it was replaced with the data.DataRepetitionSelector interface.

Could you please replace in sunburst.ts file: 
DataViewScopeIdentity with data.DataRepetitionSelector

**Comment by ignatvilesov** [comment]
Please use `npm start` to start dev server. We include PBIVIZ into local dependencies to work with lots of visuals at the same time with reinstalling global pbiviz

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
