### ISSUE TITLE
Visual will not release color bands after selected

### ISSUE THREAD

**Issue by chuckb1300** [Microsoft/powerbi-visuals-sunburst#4]
Visual will not release color bands after selected.
1) Select colored section and other visual parts are grayed out.
2) Click the same colored section as before and it should reset to full display and does not.

3) in addition, some colors
![capture4](https://cloud.githubusercontent.com/assets/26283440/23716393/f7fce734-03e4-11e7-97e5-a15c81ab4a3b.PNG)
 (which you can not alter) do not show labels such as black.

**Comment by ignatvilesov** [comment]
It has been implemented in [Sunburst 1.5.0](https://github.com/Microsoft/powerbi-visuals-sunburst/releases/tag/1.5.0)
